### ISSUE TITLE
Facebook API not returning email although specified in scope

### ISSUE THREAD

**Issue by komirad** [dgeorgiev/facebook-ion-auth#3]
I am not sure if it's the new Facebook API.. but to fix this I had to add "&fields=email" to the graph_url (line 71) in libraries/Facebook_ion_auth.php

**Comment by dgeorgiev** [comment]
Hello,

Maybe facebook changed their API, I will look at it, thanks.

**Comment by designia** [comment]
Did u fix this issue?

**Comment by dgeorgiev** [comment]
@designia I didn't have time to look at it, please try the method mentioned above.

**Comment by cithukyaw** [comment]
This is likely to be fixed in #5
