### ISSUE TITLE
Erro ao alterar para produção

### ISSUE THREAD

**Issue by victorpflores** [dgeorgiev/facebook-ion-auth#8]
Testei o app em localhost e o mesmo funcionou corretamente. Fiz upload para um servidor e o mesmo trouxe esse erro.
![Screenshot_5](https://user-images.githubusercontent.com/68913221/108574747-f9004d80-72f6-11eb-8e50-0da7a1f8c16f.png)

**Comment by dgeorgiev** [comment]
Sorry but I'm familiar with spanish? If you could try maybe english

But based on the localhost mention I believe that the url should be accessible from facebook?

**Comment by victorpflores** [comment]
Good morning, The url was inserted on facebook under "Application domains". When performing testing in development it works perfectly, but when I put it into production this error appears. Is there any place I need to configure?

**Comment by dgeorgiev** [comment]
Probably need to change the url in the Application domains with the real url instead of localhost?

**Comment by victorpflores** [comment]
It has been changed to the domain url within the facebook settings. In the api should I change anything?

**Comment by dgeorgiev** [comment]
Don't think so, maybe if you can give me the error in english? But I think the issue is in the facebook settings instead of the code.

**Comment by victorpflores** [comment]
Error follows "Unable to load the URL: The domain for this URL is not included in the application domains. In order to load this URL, all domains and subdomains are dependent on the Application domains field in the application settings."

**Comment by dgeorgiev** [comment]
Maybe you can try this https://stackoverflow.com/questions/46850461/cant-load-url-the-domain-of-this-url-isnt-included-in-the-apps-domains-in-fa

**Comment by victorpflores** [comment]
Thank you very much.
