### ISSUE TITLE
Error update email

### ISSUE THREAD

**Issue by victorpflores** [dgeorgiev/facebook-ion-auth#9]
When changing the email and also the username, the following error appeared: "Username in use or invalid. Account information could not be updated". I have enabled ion-auth email activation. Can you help me?

**Comment by dgeorgiev** [comment]
Sorry I haven't worked with facebook login a long time, so no idea why would that happen.

**Comment by victorpflores** [comment]
Good morning,

I'm not using facebook login. This happens with ion-auth

**Comment by dgeorgiev** [comment]
You can try asking maybe in the ion-auth repo? Unfortunately I haven't worked with it in a few years so can't be really helpful.
